chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room')
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('sign_up/', views.sign_up,name='sign_up'),
    path('password_reset/', views.password_reset, name="password_reset"),
    path('delete_account/', views.delete_account, name="delete_account"),
    path('password_reset_request/', views.password_reset_request, name="password_reset_request"),
    path('password_reset/', views.password_reset, name='password_reset')
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import TodoList, TodoDetail

app_name = 'todo_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('change_status', views.change_status, name='change_status'),
    path('completed_todos/', views.completed_todos, name='completed_todos'),
    path('delete_todo/', views.delete_todo, name='delete_todo'),
    path('api/v1/', TodoList.as_view()),
    path('api/v1/<int:pk>/', TodoDetail.as_view()),
    path('api/v1/rest-auth/', include('rest_auth.urls'))
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
    path('chat/', include('chat.urls'))
]

ipfilter_middleware/models.py
from django.db import models

# Create your models here.

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

# Create your models here.


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}"

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text} - {self.status}"

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return self.user.username

# Create your models here.

chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html')


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
        })

ipfilter_middleware/views.py
from django.shortcuts import render

# Create your views here.

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from .models import PasswordResetRequest
from django.contrib.auth.decorators import login_required
import django_rq
from . messaging import email_message


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(request, username=request.POST["user"], password=request.POST["password"])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('todo_app:index'))
        else:
            context = {
                'error': 'Bad username or password'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'login_app/login.html')


def password_reset_request(request):
    if request.method == "POST":
        post_user = request.POST["user"]
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            django_rq.enqueue(email_message, {
               'token' : prr.token,
               'email' : prr.user.email,
               })
            return HttpResponseRedirect(reverse('login_app:password_reset'))

    return render(request, 'login_app/password_reset_request.html')


def password_reset(request):
    if request.method == "POST":
        post_user = request.POST['user']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.object.get(token=token)
                prr.save()
            except:
                print("Invalid password reset attempt.")
                return render(request, 'login_app/password_reset.html')

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('login_app:login'))

    return render(request, 'login_app/password_reset.html')


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        username = request.POST['user']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'login_app/sign_up.html', context)


@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST["confirm_deletion"] == "DELETE":
            user = authenticate(request, username=request.user.username, password=request.POST["password"])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                print("fail delete")
    return render(request, 'login_app/delete_account.html')

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Todo
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    if request.method == "POST":
        text = request.POST["text"]
        todo = Todo()
        todo.text = text
        todo.save()

    todos = Todo.objects.filter(status=False)
    context = {
        'todos':todos
    }
    return render(request, 'todo_app/index.html', context)


@login_required
def change_status(request):
    pk = request.POST["pk"]
    todo = get_object_or_404(Todo, pk=pk)
    if "checked" in request.POST:
        todo.status = True
    else:
        todo.status = False
    todo.save()
    return HttpResponseRedirect(reverse('todo_app:index'))


@login_required
def completed_todos(request):
    todos = Todo.objects.filter(status=True)
    context = {
        'todos': todos
    }
    return render(request, 'todo_app/completed_todos.html', context)


@login_required
def delete_todo(request):
    print(request.META['HTTP_REFERER'])
    pk = request.POST["pk"]
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
        return HttpResponseRedirect(reverse('todo_app:index'))
    else:
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))

user_profile/views.py
from django.shortcuts import render

# Create your views here.

chat/templates/chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_app/login_app.css' %}" />
    <title>Account</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

login_app/templates/login_app/delete_account.html
{% extends "login_app/base.html" %}
{% block content %}
<h1>Delete Account</h1>
<hr>
<form action="{% url 'login_app:delete_account' %}" method="POST">
    {% csrf_token %}
    <input type="password" name="password" placeholder="Password">
    <input type="text" name="confirm_deletion" placeholder="Type DELETE">
    <br>
    <button>Submit</button>
</form>
{% endblock %}

login_app/templates/login_app/login.html
{% extends "login_app/base.html" %}
{% block content %}
<h1>Login</h1>
<a href="{% url 'login_app:sign_up' %}">Sign Up</a> <!--url login_app:sign_up-->
<hr>
<form action="{% url 'login_app:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name">
    <input type="password" name="password" placeholder="Password">
    <button>Login</button>
</form>
<hr>
<a href="{% url 'login_app:password_reset_request' %}">Forgot Password</a>
{% if error %}
    {{ error }}
{% endif %}
{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends "login_app/base.html" %}
{% block content %}
<h1>Reset Password</h1>
<hr>
<form action="{% url 'login_app:password_reset' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name">
    <br>
    <input type="password" name="password" placeholder="New Password">
    <br>
    <input type="password" name="confirm_password" placeholder="Repeat Password">
    <br>
    <input type="text" name="token" placeholder="Code">
    <br>
    <button>Submit</button>
</form>
{% endblock %}

login_app/templates/login_app/password_reset_request.html
{% extends "login_app/base.html" %}
{% block content %}
<h1>Request Reset Password</h1>
<hr>
<form action="{% url 'login_app:password_reset_request' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name">
    <input type="email" name="email" placeholder="Email">
    <button>Submit</button>
</form>
{% endblock %}

login_app/templates/login_app/sign_up.html
{% extends "login_app/base.html" %}
{% block content %}
<h1>Sign Up</h1>
<a href="{% url 'login_app:login' %}">Login</a>
<!--url login_app:sign_up-->
<hr>
<form action="{% url 'login_app:sign_up' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name">
    <input type="email" name="email" placeholder="Email">
    <input type="password" name="password" placeholder="Password">
    <input type="password" name="confirm_password" placeholder="Confirm Password">
    <button>Sign Up</button>
</form>
<hr>
{% if error %}
{{ error }}
{% endif %}
{% endblock %}

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo_app/todo_app.css' %}"/>
    <title>Todos</title>
</head>
<body>
    <p>Welcome {{ user }} - <a href="{% url 'login_app:logout' %}">Logout</a> - <a href="{% url 'login_app:delete_account' %}">Delete Account</a></p>
    <hr>
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
</body>
</html>

todo_app/templates/todo_app/completed_todos.html
{% extends "todo_app/base.html" %}

{% block content %}
    <h1>Completed Todo</h1>
    <hr>
    <ul>
        {% for todo in todos %}
        <li>
            <form action="{% url 'todo_app:change_status' %}" method="POST">
                {% csrf_token %}
                 <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %}>
                    <button>Update</button>
                    <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                <input type="hidden" name="pk" value="{{ todo.pk }}">
                {{ todo.text }}
            </form>
        </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
<a href="{% url 'todo_app:index' %}">Todos</a>
{% endblock %}

todo_app/templates/todo_app/index.html
{% extends "todo_app/base.html" %}
    {% block content %}
    <h1>Todo</h1>
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" name="text" placeholder="Write Todo"/>
        <button>Create Todo</button>
    </form>
    <hr>
    <ul>
        {% for todo in todos %}
        <li>
            <form action="{% url 'todo_app:change_status' %}" method="POST">
                {% csrf_token %}
                 <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %}>
                    <button>Update</button>
                    <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                <input type="hidden" name="pk" value="{{ todo.pk }}">
                {{ todo.text }}
            </form>
        </li>
        {% endfor %}
    </ul>
  {% endblock %}
{% block footer %}
    <a href="{% url 'todo_app:completed_todos' %}">Completed</a>
{% endblock %}